catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # '' represents the root route localhost:8000
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
# import all the functions from the views.py file
# and attach them to the variable named views
from . import views

urlpatterns = [
    # localhost:8000
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # route for our cats index
    # we cats_index, since all of our routes go in the same file
    # later on we mights have toys_index
    path('cats/', views.cats_index, name='index'),
    # cats detail (show page)
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/create', views.CatCreate.as_view(), name='cats_create'),
    # CBV (Class Based View) expect the params to be int:pk (primary key) "The convention name"
    path('cats/<int:pk>/update/',
         views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/',
         views.CatDelete.as_view(), name='cats_delete'),
		 # One to many route
    path('cats/<int:cat_id>/add_feeding/',
         views.add_feeding, name='add_feeding'),
		 # one to many route
	path('cats/<int:cat_id>/add_photo/', views.add_photo, name='add_photo'),
	# Many to Many route
	path('cats/<int:cat_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
	## CBV always label your params as <int:pk> because thats how they are preconfigured
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User # importing the user model
from django.urls import reverse  # kind of like redirect
# Create your models here.


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


# One Cat has many feedings
# cat.<related_model_name<_set.all(), .create(), .get, .filter
# cat.feeding_set


class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    # A User has many cats, cat belongs to a User
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # the related model must be defined first because there is no hoisting
	# toy has to be defined before you can reference
    toys = models.ManyToManyField(Toy)
    # This function happens when our create form or update form is submitted,
    # and CatsCreate CBV after it has handled the post request
    # or CatsUpdate CBV handles the PUT request

    def get_absolute_url(self):
        # path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
        # self.id is referring to the cat that was just created
        # when the submit the form
        return reverse('detail', kwargs={'cat_id': self.id})

    def __str__(self):
        return f"{self.name} is {self.age} years old"


class Photo(models.Model):
	# url of the image on aws
    url = models.CharField(max_length=200)
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for cat_id: {self.cat_id} @{self.url}"


# All Caps in python, This is a convention that says
# this variable should never be overwritten
MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner'),
)
# select menus ^
# One Cat has Many Feedling, Feeding belongs to a Cat


class Feeding(models.Model):
    date = models.DateField('feeding date')
    # meal will be represented by a single letter (B)reakfast, (L)unch, (D)inner
    # # we set the default value for meal to 'B
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0])
    # Create a cat_id FK
    # models.CASCADE, if we delete a cat, delete its feedings as well
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        # get_meal_display is automatically generated,
        # on inputs that have choices parameter, see meal
        return f"{self.get_meal_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding 

class FeedingForm(ModelForm):
	class Meta:
		model = Feeding 
		fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
# Create your views here.
from django.http import HttpResponse

import uuid # this helps generate random numbers for naming our files on aws, they all have to be unique names, so we can prepend random numbers to the filename
import boto3 # the aws sdk that allows us to talk to aws s3
from .models import Cat, Toy, Photo
from botocore.exceptions import ClientError

from django.contrib.auth import login # login function accepts a user to log them in
from django.contrib.auth.forms import UserCreationForm

from .forms import FeedingForm

### Authorization tools!
# for a view functions
from django.contrib.auth.decorators import login_required
# for our Class Based Views
from django.contrib.auth.mixins import LoginRequiredMixin




def signup(request):
	# handle the get request, which should return the form
	# handle the POST request, which take the contents of the form, create the user, 
	# and log them in
	error_message = ''
	if request.method == 'POST':
		# create the user object from our form
		# request.POST is like req.body
		form = UserCreationForm(request.POST)
		if form.is_valid():
			# add the user to the database
			user = form.save()
			# login the user
			login(request, user)# this adds the user's id to your session cookie, and 
			# make request.user availiable in all of your view functions
			return redirect('index')
		else: 
			error_message = 'Invalid sign up - try again'
	
	# Here is handling the GET request
	form = UserCreationForm()
	return render(request, 'registration/signup.html', {'error_message': error_message, 'form': form})






###==================================================
### ALERT ==================================================
# write your bucket name!
### IF YOU FETCH UPDATE THIS TO YOUR BUCKET NAME and UPDATE YOUR S3_BASE_URL to yours
BUCKET = 'emilymerrow'
S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
###==================================================
###==================================================

@login_required
def add_photo(request, cat_id):
	# photo-file will be the "name" attribute on the <input name='photo-file' type='file'>
	photo_file = request.FILES.get('photo-file', None)
	if photo_file:
		# setup the aws client 
		s3 = boto3.client('s3')
		# Make a unique name to store the photo			# franklin.png
														# photo_file.name.rfind('.'): this gets us the file exstension .png
			 # store the file in a catcollector folder/randomnumber + the file name with the extension
		key = 'catcollector/' + uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
		try:
			s3.upload_fileobj(photo_file, BUCKET, key)
			# build the url string of where it is hosted to store db
			url = f"{S3_BASE_URL}{BUCKET}/{key}"
			# add it to the db
			Photo.objects.create(url=url, cat_id=cat_id)
		except ClientError as e:
			print(e, " error from aws!")
		
	return redirect('detail', cat_id=cat_id)





# the arguments come from the params in the urls.py
# 'cats/<int:cat_id>/assoc_toy/<int:toy_id>/'
@login_required
def assoc_toy(request, cat_id, toy_id):
	# associating a cat with a toy
	Cat.objects.get(id=cat_id).toys.add(toy_id)

	# One line version of below ^
	# cat = Cat.object.get(id=cat_id)
	# cat.toys.add(toy_id)

	return redirect('detail', cat_id=cat_id)



# cat_id matches the url
# path('cats/<int:cat_id>/add_feeding/'
def add_feeding(request, cat_id):
    # create a modelForm instance using the information from the post request
    # request.POST is like req.body
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't want to save it until we add the cat_id to the feeding
        new_feeding = form.save(commit=False)
        # tying the cat to the feeding
        # defining the FK
        new_feeding.cat_id = cat_id
        new_feeding.save()
        # import redirect on the top line from django.shortcuts
    return redirect('detail', cat_id=cat_id)

# Handles GET AND POST of the form
# The form expectations is templates/<name_of_app>/<model_form.html
# templates/main_app/cat_form.html
# CBV class based view


class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    # fields says what fields on our model should be included in the form
    fields = ['name', 'breed', 'description', 'age']  # all the fields
    # fields = ['breed', 'description', 'age'] # you can choose the fields
    # from your model if you don't want to include every field
    # success_url = '/cats/' # redirect to the list page
    #inherited method from CreateView
    def form_valid(self, form):
        # assing the logged in user (self.request.user)
        # to the the form instance that is being submitted when we 
        # send a post request ot the server
        form.instance.user = self.request.user
        # Let the createview do the rest of its job
        return super().form_valid(form)


# The form expectations is templates/<name_of_app>/<model_form.html
# templates/main_app/cat_form.html
# Same form as the create!
class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    # disallow the name as input on the form, so no one can update the name
    fields = ['breed', 'description', 'age']

# templates/<name_of_app>/<model>_confirm_delete.html
# templates/main_app/cat_confirm_delete.html


class CatDelete(DeleteView):
    model = Cat
    # since we can't redirect to a detail page of a cat we deleted
    success_url = '/cats/'

@login_required
def cats_index(request):

    # key 'cats' will be the variable name in the cats/index.html
    # cats will be the array that we are storing in the 'cats' variable
    cats = Cat.objects.filter(user=request.user)  # finding all the cats from the database!
    return render(request, 'cats/index.html', {'cats': cats})

# path('cats/<int:cat_id>/', views.cats_detail, name='detail'), <- urls.py
# <int: cat_id> that must be the argument to your detail function
# cat_id is the param


def cats_detail(request, cat_id):
    # find the cat with the id that was in the params in the db
    cat = Cat.objects.get(id=cat_id)
    # Find all the toys not in the cat.toys.all() array

    # cat.toys.all().values_list('id') <- this finds all the cats toys and returns a list
    # of just their id's
    #  Find all toys that are not in the cat.toys id list
	# id__in <- Field Look up, theser for complicated queries 
    toys_cat_doesnt_have = Toy.objects.exclude(
        id__in=cat.toys.all().values_list('id'))

    # creating a form (instance) from our FeedingForm class!
    feeding_form = FeedingForm()
    return render(request, 'cats/detail.html', {
		'cat': cat, 
		'feeding_form': feeding_form, 
		'toys': toys_cat_doesnt_have
	})


def home(request):
    return render(request, 'home.html')


def about(request):
    # django is configured to know automatically
    # to look inside of a templates folder for the html files
    return render(request, 'about.html')


class ToyList(ListView):
    model = Toy


class ToyDetail(DetailView):
    model = Toy


class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'


class ToyUpdate(UpdateView):
    model = Toy
    fields = ['name', 'color']


class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'

main_app/templates/cats/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat Details</h1>

<div class="row">
	<div class="col s6">
		<div class="card">
			<div class="card-content">
				<span class="card-title">{{ cat.name }}</span>
				<p>Breed: {{ cat.breed }}</p>
				<p>Description: {{ cat.description }}</p>
				{% if cat.age > 0 %}
				<p>Age: {{ cat.age }}</p>
				{% else %}
				<p>Age: Kitten</p>
				{% endif %}
			</div>
			<div class="card-action">
				<a href="{% url 'cats_update' cat.id %}">Edit</a>
				<a href="{% url 'cats_delete' cat.id %}">Delete</a>
			</div>
		</div> 
		<!-- the end of class card -->


		{% for photo in cat.photo_set.all %}
		<img class="responsive-img card-panel" src="{{photo.url}}">
		{% empty %}
		<div class="card-panel teal-text center-align">No Photos Uploaded</div>
		{% endfor %}

		<form action="{% url 'add_photo' cat.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
			{% csrf_token %}
			<input type="file" name="photo-file">
			<br><br>
			<input type="submit" class="btn" value="Upload Photo">
		</form>

	</div>
	<div class="col s6">

		<form action="{% url 'add_feeding' cat.id %}" method="POST">
			{% csrf_token %}
			{{ feeding_form.as_p }}
			<input type="submit" class="btn" value="Add Feeding">
		</form>

		<table class="striped">
			<thead>
				<tr>
					<th>Date</th>
					<th>Meal</th>
				</tr>
			</thead>
			<tbody>
				{% for feeding in cat.feeding_set.all %}
				<tr>
					<td>{{feeding.date}}</td>
					<td>{{feeding.get_meal_display}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

<hr>
<div class="row">
	<div class="col s6">
		<h3>{{ cat.name }}'s Toys</h3>
		{% if cat.toys.count %}
		{% for toy in cat.toys.all %}
		<div class="card">
			<div class="card-content">
				<span class="card-title">
					A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
				</span>
			</div>
		</div>
		{% endfor %}
		{% else %}
		<h5>No Toys :(</h5>
		{% endif %}
	</div>
	<!-- Available toys will come after this line -->
	<div class="col s6">
		<h3>Available Toys</h3>
		{% if toys.count %}
		{% for toy in toys.all %}
		<div class="card">
			<div class="card-content">
				<span class="card-title">
					A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
				</span>
			</div>
			<div class="card-action">
				<form action="{% url 'assoc_toy' cat.id toy.id %}" method="post">
					{% csrf_token %}
					<button type="submit" class="btn">Add</button>
				</form>
			</div>
		</div>
		{% endfor %}
		{% else %}
		<h5>{{cat.name}} Already Has All Toys Available</h5>
		{% endif %}
	</div>
</div>

<script>

	const dateEl = document.querySelector('#id_date');
	M.Datepicker.init(dateEl, {
		format: 'yyyy-mm-dd', // this how django formats the date in the model
		defaultDate: new Date(),
		setDefaultDate: true,
		autoClose: true
	})


	const selectEl = document.querySelector('#id_meal');
	M.FormSelect.init(selectEl)

</script>


{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Cat List</h1>


{% for cat in cats %}
<a href="{% url 'detail' cat.id %}">
	<div class="card">
		<div class="card-content">
			<span class="card-title">{{ cat.name }}</span>
			<p>Breed: {{ cat.breed }}</p>
			<p>Description: {{ cat.description }}</p>
			{% if cat.age > 0 %}
			<p>Age: {{ cat.age }}</p>
			{% else %}
			<p>Age: Kitten</p>
			{% endif %}
		</div>
	</div>
</a>
{% endfor %}

{% endblock %}